//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVLite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source={0};Persist Security Info=False;")]
        public string ConnectionStringFormat {
            get {
                return ((string)(this["ConnectionStringFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KVLite.FileCache.CachePath")]
        public string AppSettings_CachePathKey {
            get {
                return ((string)(this["AppSettings_CachePathKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FileCache.kvlite")]
        public string DefaultCachePath {
            get {
                return ((string)(this["DefaultCachePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE TABLE [Cache_Item] (\r\n  [Partition] NVARCHAR(100) NOT NULL,\r\n  [Key] NVARC" +
            "HAR(100) NOT NULL,\r\n  [Value] IMAGE NOT NULL,\r\n  [Expiry] DATETIME,\r\n  [Interval" +
            "] BIGINT,\r\n  CONSTRAINT Cache_Item_PK PRIMARY KEY ([Partition], [Key])\r\n);")]
        public string CacheCreationScript {
            get {
                return ((string)(this["CacheCreationScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string DefaultPartition {
            get {
                return ((string)(this["DefaultPartition"]));
            }
        }
    }
}
