language: csharp
dotnet: 2.0.0
dist: trusty

before_script:
  - chmod a+x ./build.sh

script:
  - git fetch --unshallow
  - ./build.sh

notifications:
  email:
    on_success: change
    on_failure: change
