  DROP TABLE "KVLITE"."KVL_CACHE_ITEMS";

  CREATE TABLE "KVLITE"."KVL_CACHE_ITEMS" 
   (	
    "KVLI_HASH" NUMBER(20,0) NOT NULL ENABLE, 
	"KVLI_EXPIRY" NUMBER(20,0) NOT NULL ENABLE, 
	"KVLI_INTERVAL" NUMBER(20,0) NOT NULL ENABLE,
	"KVLI_VALUE" BLOB NOT NULL ENABLE, 
	"KVLI_COMPRESSED" NUMBER(1,0) NOT NULL ENABLE, 
	"KVLI_PARTITION" NVARCHAR2(255) NOT NULL ENABLE, 
	"KVLI_KEY" NVARCHAR2(255) NOT NULL ENABLE, 
	"KVLI_CREATION" NUMBER(20,0) NOT NULL ENABLE, 
	"KVLI_PARENT_HASH0" NUMBER(20,0), 
	"KVLI_PARENT_KEY0" NVARCHAR2(255), 
	"KVLI_PARENT_HASH1" NUMBER(20,0), 
	"KVLI_PARENT_KEY1" NVARCHAR2(255), 
	"KVLI_PARENT_HASH2" NUMBER(20,0), 
	"KVLI_PARENT_KEY2" NVARCHAR2(255), 
	"KVLI_PARENT_HASH3" NUMBER(20,0), 
	"KVLI_PARENT_KEY3" NVARCHAR2(255), 
	"KVLI_PARENT_HASH4" NUMBER(20,0), 
	"KVLI_PARENT_KEY4" NVARCHAR2(255), 
	 CONSTRAINT "PK_KVLI" PRIMARY KEY ("KVLI_HASH") ENABLE,
     CONSTRAINT "FK_KVLI_PARENT0" FOREIGN KEY ("KVLI_PARENT_HASH0")
	  REFERENCES "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_HASH") ON DELETE CASCADE ENABLE,
     CONSTRAINT "FK_KVLI_PARENT1" FOREIGN KEY ("KVLI_PARENT_HASH1")
	  REFERENCES "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_HASH") ON DELETE CASCADE ENABLE,
     CONSTRAINT "FK_KVLI_PARENT2" FOREIGN KEY ("KVLI_PARENT_HASH2")
	  REFERENCES "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_HASH") ON DELETE CASCADE ENABLE,
     CONSTRAINT "FK_KVLI_PARENT3" FOREIGN KEY ("KVLI_PARENT_HASH3")
	  REFERENCES "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_HASH") ON DELETE CASCADE ENABLE,
     CONSTRAINT "FK_KVLI_PARENT4" FOREIGN KEY ("KVLI_PARENT_HASH4")
	  REFERENCES "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_HASH") ON DELETE CASCADE ENABLE
   )
   LOB ("KVLI_VALUE") STORE AS (CACHE READS ENABLE STORAGE IN ROW);
 

   COMMENT ON COLUMN "KVLITE"."KVL_CACHE_ITEMS"."KVLI_HASH" IS 'Hash of partition and key computed with xxHash';
 

  CREATE INDEX "KVLITE"."IX_KVLI_EXP_PART" ON "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_EXPIRY", "KVLI_PARTITION");


  CREATE INDEX "KVLITE"."FK_KVLI_PARENT0" ON "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_PARENT_HASH0");
 

  CREATE INDEX "KVLITE"."FK_KVLI_PARENT1" ON "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_PARENT_HASH1");
 

  CREATE INDEX "KVLITE"."FK_KVLI_PARENT2" ON "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_PARENT_HASH2");
 

  CREATE INDEX "KVLITE"."FK_KVLI_PARENT3" ON "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_PARENT_HASH3");
 

  CREATE INDEX "KVLITE"."FK_KVLI_PARENT4" ON "KVLITE"."KVL_CACHE_ITEMS" ("KVLI_PARENT_HASH4");